# 2.1 数据操作：PyTorch 张量基础

目标：理解张量的形状、重塑、索引、运算、广播和 GPU 移动。请按顺序运行，并先猜测每个代码块的输出。

In [1]:
import torch

print('PyTorch 版本:', torch.__version__)
print('CUDA 可用:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

PyTorch 版本: 2.5.1+cu121
CUDA 可用: True
GPU: NVIDIA GeForce RTX 4050 Laptop GPU


## 1. 创建张量

标量是 0 维，向量是 1 维，矩阵是 2 维。更高维的数据也统一称为张量。

In [2]:
scalar = torch.tensor(7)
vector = torch.tensor([1.0, 2.0, 3.0])
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

print('标量:', scalar, 'shape =', scalar.shape)
print('向量:', vector, 'shape =', vector.shape)
print('矩阵:\n', matrix, 'shape =', matrix.shape)

标量: tensor(7) shape = torch.Size([])
向量: tensor([1., 2., 3.]) shape = torch.Size([3])
矩阵:
 tensor([[1., 2.],
        [3., 4.]]) shape = torch.Size([2, 2])


## 2. 形状与 reshape

`reshape` 可以改变排列方式，但不能改变元素总数。

In [3]:
x = torch.arange(12)
X = x.reshape(3, 4)

print('原张量:', x)
print('原形状:', x.shape)
print('重塑后:\n', X)
print('新形状:', X.shape)
print('元素数量:', X.numel())

原张量: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
原形状: torch.Size([12])
重塑后:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
新形状: torch.Size([3, 4])
元素数量: 12


### 动手实验 A

把上面的 `reshape(3, 4)` 分别改成 `reshape(4, 3)`、`reshape(2, 6)` 和 `reshape(3, 5)`。记录哪些成功、哪个失败，并解释原因。

In [4]:
# 在这里完成实验 A


## 3. 索引与切片

In [5]:
print('第一行:', X[0])
print('最后一行:', X[-1])
print('第 2 行第 3 列:', X[1, 2])
print('前两行:\n', X[:2])

第一行: tensor([0, 1, 2, 3])
最后一行: tensor([ 8,  9, 10, 11])
第 2 行第 3 列: tensor(6)
前两行:
 tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


## 4. 运算与广播

广播会在形状兼容时自动扩展长度为 1 的维度。

In [6]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)

print('a 的形状:', a.shape)
print('b 的形状:', b.shape)
print('a + b =\n', a + b)
print('结果形状:', (a + b).shape)

a 的形状: torch.Size([3, 1])
b 的形状: torch.Size([1, 2])
a + b =
 tensor([[0, 1],
        [1, 2],
        [2, 3]])
结果形状: torch.Size([3, 2])


### 动手实验 B

不用运行，先在纸上写出 `a + b` 的结果，再运行验证。然后说明为什么结果是 `3 × 2`。

In [7]:
# 用一句话记录你的解释
broadcast_explanation = ''
print(broadcast_explanation)

## 5. 在 GPU 上计算

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
gpu_matrix = torch.randn(1000, 1000, device=device)
result = gpu_matrix @ gpu_matrix

print('计算设备:', result.device)
print('结果形状:', result.shape)

计算设备: cuda:0
结果形状: torch.Size([1000, 1000])


## 完成标准

- 所有代码块成功运行。
- 完成实验 A 和 B。
- 能用自己的话解释 `shape`、`reshape` 和广播。
- 把心得写入 `notes/chapter02.md`。